### ISSUE TITLE
Dry home page + logo

### ISSUE THREAD

**Issue by sparshmehta** [abhishek776/Net-Impact-Website#6]
The home page seems a little dry. Not the best with design, but I have attached a simple suggestion to make it a little more alive. I would definitely include the logo on the top left so people can click on it and be directed to home. Also, we should have the logo on the website front page.

![nib website suggestion](https://cloud.githubusercontent.com/assets/10661727/9232556/f6a6ef7c-414b-11e5-97a3-201f5c9264b2.png)

**Comment by abhishek776** [comment]
done
