### ISSUE TITLE
Mission Statement

### ISSUE THREAD

**Issue by sparshmehta** [abhishek776/Net-Impact-Website#8]
This mission statement is weird. 

Suggestion:
Through our focus on social and environmental impact, innovative methods, and diverse backgrounds, Net Impact Berkeley strives to bring responsibility to business and innovation to responsibility 

![screen shot 2015-08-12 at 11 10 29 pm](https://cloud.githubusercontent.com/assets/10661727/9232772/25b6354c-414d-11e5-9c95-7f1b3d009f3f.png)

**Comment by abhishek776** [comment]
done
